node_addr: http://213.239.193.208:9053
http_client_timeout_duration_secs: 5
chain_sync_starting_height: 905349
backlog_config:
  order_lifespan: 86400
  order_exec_time: 86400
  retry_suspended_prob: 20
log4rs_yaml_path: conf/log4rs.yaml
backlog_store_db_path: ./tmp/backlog
entity_repo_db_path: ./tmp/pools
program_repo_db_path: ./tmp/programs
bundle_repo_db_path: ./tmp/bundles
funding_repo_db_path: ./tmp/funding
schedule_repo_db_path: ./tmp/schedule