[package]
name = "spectrum-offchain"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.13"
futures = "0.3.25"
tokio = { version = "1.22.0", features = ["full"] }
ergo-chain-sync = {  version = "0.1.0", path = "../ergo-chain-sync" }