name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Tests on ubuntu-latest
    runs-on: ubuntu-latest

    # Service container to run `redis` 
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: build and run tests
        run: |
          cargo test -- --test-threads=1